### ISSUE TITLE
[질문] Spring Batch에서 Multi DataSource 설정 및 트랜잭션 관리 관련 질문

### ISSUE THREAD

**Issue by chobuisness** [geminiKim/development-practice#108]
안녕하세요 제미니님. 유튜브 잘 보고 있습니다. 새해 복 많이 받으세요 ㅎㅎ

현재 프로젝트에서 Batch 모듈을 독립적으로 운영하며, 서비스 애플리케이션과 분리된 실행 구조를 계획하고 있습니다. (제미니님 spring template 기반)
Batch 관련 meta 테이블을 별도의 데이터베이스에서 관리하는 방향으로 결정했는데, 이에 대해 몇 가지 궁금한 점이 있습니다.

### 1. Batch용 DataSource 설정 위치
배치 관련 DataSource를 어디에서 정의하는 것이 더 적절할지 고민하고 있습니다.

**(1) storage:db-core 모듈에서 설정**
```yml
# db-core.yml
spring.config.activate.on-profile: local

storage:
  datasource:
    core:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      pool-name: core-db-pool
      data-source-properties:
        rewriteBatchedStatements: true
    batch:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:batch;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      pool-name: core-batch-pool
      data-source-properties:
        rewriteBatchedStatements: true
```

Meta 테이블 또한 DB와 관련이 있으므로 `storage:db-core` 모듈에서 관리하도록 설정
하지만 이렇게 하면 서비스 애플리케이션에서도 Batch 관련 설정이 함께 로드됨
따라서 profile 을 분리하거나 `storage:db-batch` 모듈을 만들어 개념적으로 분리하는 것이 좋을까? 라는 고민이 있습니다.

**(2) Batch 모듈에서 직접 DataSource 설정**
Batch 모듈 내부에서 `@Configuration` 클래스를 통해 `DataSource` 및 `TransactionManager` 설정
이렇게 하면 별도 `storage:db-batch` 모듈을 만들 필요 없이, Batch 모듈이 자체적으로 관리 가능

어떤 방식이 더 바람직한지 궁금합니다.

### 2. Multi DataSource 사용 시 트랜잭션 관리
```java
@Configuration
public class BatchCoreDataSourceConfig {

	@Bean
	@ConfigurationProperties(prefix = "spring.datasource.batch")
	public HikariConfig batchHikariConfig() {
		return new HikariConfig();
	}

	@Primary
	@Bean("batchDataSource")
	public DataSource dataSource(@Qualifier("batchHikariConfig") HikariConfig config) {
		return new HikariDataSource(config);
	}

	@Primary
	@Bean("batchTransactionManager")
	public PlatformTransactionManager transactionManager(@Qualifier("batchDataSource") DataSource dataSource) {
		return new JdbcTransactionManager(dataSource);
	}
}

@Configuration
@EnableBatchProcessing
public class BatchConfig {

	@Bean("batchCoreJobRepository")
	public JobRepository jobRepository(
		@Qualifier("batchDataSource") DataSource dataSource,
		@Qualifier("batchTransactionManager") PlatformTransactionManager transactionManager
	) throws Exception {
		JobRepositoryFactoryBean factoryBean = new JobRepositoryFactoryBean();
		factoryBean.setDataSource(dataSource);
		factoryBean.setTransactionManager(transactionManager);
		factoryBean.afterPropertiesSet();
		return factoryBean.getObject();
	}
}

```

현재는 Batch 모듈에서 meta 테이블을 위한 JobRepository 트랜잭션과, 비즈니스 테이블을 위한 트랜잭션이 분리되어 있습니다.

JobRepository는 datasource.batch를 사용하여 meta 테이블을 관리
Step에서는 datasource.core를 사용하여 비즈니스 로직을 수행
따라서, 각 Step에서 사용할 PlatformTransactionManager를 별도로 정의하여 주입

**이런 구조에서 두 개의 트랜잭션을 동기화해야 하는지, 혹은 각기 독립적으로 관리해도 되는지 궁금합니다.**
현재로서는 JobRepository와 Step이 별도의 트랜잭션을 가지며, Step에서 예외가 발생해도 JobRepository는 정상적으로 실패 상태를 기록하는 것으로 이해하고 있습니다.

하지만 동기화가 필요하다면 JTA 등 분산 트랜잭션을 고려해야 할까요?
혹시 추천해주실 최적의 트랜잭션 관리 방식이 있을지 궁금합니다.
